FROM golang:1.21-alpine as builder
RUN go install github.com/improbable-eng/grpc-web/go/grpcwebproxy@latest

FROM alpine:latest
COPY --from=builder /go/bin/grpcwebproxy /usr/local/bin/
# These flags connect the proxy to your backend service in Kubernetes
ENTRYPOINT ["grpcwebproxy"]
CMD ["--backend_addr=poker-backend-svc:50051", "--run_tls_server=false", "--allow_all_origins"]
