// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.33.4
// source: proto/poker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PokerServiceClient is the client API for PokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PokerServiceClient interface {
	// Task: 2 cards + 5 cards => best hand
	EvaluateHand(ctx context.Context, in *HandRequest, opts ...grpc.CallOption) (*HandResponse, error)
	// Task: Compare two sets of hands
	CompareHands(ctx context.Context, in *CompareRequest, opts ...grpc.CallOption) (*CompareResponse, error)
	// Task: Monte Carlo probability
	CalculateProbability(ctx context.Context, in *SimRequest, opts ...grpc.CallOption) (*SimResponse, error)
}

type pokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPokerServiceClient(cc grpc.ClientConnInterface) PokerServiceClient {
	return &pokerServiceClient{cc}
}

func (c *pokerServiceClient) EvaluateHand(ctx context.Context, in *HandRequest, opts ...grpc.CallOption) (*HandResponse, error) {
	out := new(HandResponse)
	err := c.cc.Invoke(ctx, "/poker.PokerService/EvaluateHand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerServiceClient) CompareHands(ctx context.Context, in *CompareRequest, opts ...grpc.CallOption) (*CompareResponse, error) {
	out := new(CompareResponse)
	err := c.cc.Invoke(ctx, "/poker.PokerService/CompareHands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerServiceClient) CalculateProbability(ctx context.Context, in *SimRequest, opts ...grpc.CallOption) (*SimResponse, error) {
	out := new(SimResponse)
	err := c.cc.Invoke(ctx, "/poker.PokerService/CalculateProbability", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PokerServiceServer is the server API for PokerService service.
// All implementations must embed UnimplementedPokerServiceServer
// for forward compatibility
type PokerServiceServer interface {
	// Task: 2 cards + 5 cards => best hand
	EvaluateHand(context.Context, *HandRequest) (*HandResponse, error)
	// Task: Compare two sets of hands
	CompareHands(context.Context, *CompareRequest) (*CompareResponse, error)
	// Task: Monte Carlo probability
	CalculateProbability(context.Context, *SimRequest) (*SimResponse, error)
	mustEmbedUnimplementedPokerServiceServer()
}

// UnimplementedPokerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPokerServiceServer struct {
}

func (UnimplementedPokerServiceServer) EvaluateHand(context.Context, *HandRequest) (*HandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateHand not implemented")
}
func (UnimplementedPokerServiceServer) CompareHands(context.Context, *CompareRequest) (*CompareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompareHands not implemented")
}
func (UnimplementedPokerServiceServer) CalculateProbability(context.Context, *SimRequest) (*SimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateProbability not implemented")
}
func (UnimplementedPokerServiceServer) mustEmbedUnimplementedPokerServiceServer() {}

// UnsafePokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PokerServiceServer will
// result in compilation errors.
type UnsafePokerServiceServer interface {
	mustEmbedUnimplementedPokerServiceServer()
}

func RegisterPokerServiceServer(s grpc.ServiceRegistrar, srv PokerServiceServer) {
	s.RegisterService(&PokerService_ServiceDesc, srv)
}

func _PokerService_EvaluateHand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServiceServer).EvaluateHand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.PokerService/EvaluateHand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServiceServer).EvaluateHand(ctx, req.(*HandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerService_CompareHands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServiceServer).CompareHands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.PokerService/CompareHands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServiceServer).CompareHands(ctx, req.(*CompareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerService_CalculateProbability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServiceServer).CalculateProbability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poker.PokerService/CalculateProbability",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServiceServer).CalculateProbability(ctx, req.(*SimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PokerService_ServiceDesc is the grpc.ServiceDesc for PokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poker.PokerService",
	HandlerType: (*PokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateHand",
			Handler:    _PokerService_EvaluateHand_Handler,
		},
		{
			MethodName: "CompareHands",
			Handler:    _PokerService_CompareHands_Handler,
		},
		{
			MethodName: "CalculateProbability",
			Handler:    _PokerService_CalculateProbability_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/poker.proto",
}
