// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.4
// source: proto/poker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HoleCards      []string `protobuf:"bytes,1,rep,name=hole_cards,json=holeCards,proto3" json:"hole_cards,omitempty"`                // e.g. ["HA", "SK"]
	CommunityCards []string `protobuf:"bytes,2,rep,name=community_cards,json=communityCards,proto3" json:"community_cards,omitempty"` // e.g. ["D2", "C7"...]
}

func (x *HandRequest) Reset() {
	*x = HandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_poker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandRequest) ProtoMessage() {}

func (x *HandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandRequest.ProtoReflect.Descriptor instead.
func (*HandRequest) Descriptor() ([]byte, []int) {
	return file_proto_poker_proto_rawDescGZIP(), []int{0}
}

func (x *HandRequest) GetHoleCards() []string {
	if x != nil {
		return x.HoleCards
	}
	return nil
}

func (x *HandRequest) GetCommunityCards() []string {
	if x != nil {
		return x.CommunityCards
	}
	return nil
}

type HandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BestHandName  string   `protobuf:"bytes,1,opt,name=best_hand_name,json=bestHandName,proto3" json:"best_hand_name,omitempty"` // e.g. "Full House"
	HandRankValue int32    `protobuf:"varint,2,opt,name=hand_rank_value,json=handRankValue,proto3" json:"hand_rank_value,omitempty"`
	BestCards     []string `protobuf:"bytes,3,rep,name=best_cards,json=bestCards,proto3" json:"best_cards,omitempty"` // The actual 5 cards forming the best hand
}

func (x *HandResponse) Reset() {
	*x = HandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_poker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandResponse) ProtoMessage() {}

func (x *HandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandResponse.ProtoReflect.Descriptor instead.
func (*HandResponse) Descriptor() ([]byte, []int) {
	return file_proto_poker_proto_rawDescGZIP(), []int{1}
}

func (x *HandResponse) GetBestHandName() string {
	if x != nil {
		return x.BestHandName
	}
	return ""
}

func (x *HandResponse) GetHandRankValue() int32 {
	if x != nil {
		return x.HandRankValue
	}
	return 0
}

func (x *HandResponse) GetBestCards() []string {
	if x != nil {
		return x.BestCards
	}
	return nil
}

type CompareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hand1 *HandRequest `protobuf:"bytes,1,opt,name=hand1,proto3" json:"hand1,omitempty"`
	Hand2 *HandRequest `protobuf:"bytes,2,opt,name=hand2,proto3" json:"hand2,omitempty"`
}

func (x *CompareRequest) Reset() {
	*x = CompareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_poker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareRequest) ProtoMessage() {}

func (x *CompareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareRequest.ProtoReflect.Descriptor instead.
func (*CompareRequest) Descriptor() ([]byte, []int) {
	return file_proto_poker_proto_rawDescGZIP(), []int{2}
}

func (x *CompareRequest) GetHand1() *HandRequest {
	if x != nil {
		return x.Hand1
	}
	return nil
}

func (x *CompareRequest) GetHand2() *HandRequest {
	if x != nil {
		return x.Hand2
	}
	return nil
}

type CompareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Winner      int32         `protobuf:"varint,1,opt,name=winner,proto3" json:"winner,omitempty"` // 1 for hand1, 2 for hand2, 0 for tie
	Hand1Result *HandResponse `protobuf:"bytes,2,opt,name=hand1_result,json=hand1Result,proto3" json:"hand1_result,omitempty"`
	Hand2Result *HandResponse `protobuf:"bytes,3,opt,name=hand2_result,json=hand2Result,proto3" json:"hand2_result,omitempty"`
}

func (x *CompareResponse) Reset() {
	*x = CompareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_poker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareResponse) ProtoMessage() {}

func (x *CompareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareResponse.ProtoReflect.Descriptor instead.
func (*CompareResponse) Descriptor() ([]byte, []int) {
	return file_proto_poker_proto_rawDescGZIP(), []int{3}
}

func (x *CompareResponse) GetWinner() int32 {
	if x != nil {
		return x.Winner
	}
	return 0
}

func (x *CompareResponse) GetHand1Result() *HandResponse {
	if x != nil {
		return x.Hand1Result
	}
	return nil
}

func (x *CompareResponse) GetHand2Result() *HandResponse {
	if x != nil {
		return x.Hand2Result
	}
	return nil
}

type SimRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HoleCards      []string `protobuf:"bytes,1,rep,name=hole_cards,json=holeCards,proto3" json:"hole_cards,omitempty"`                 // e.g. ["HA", "SK"]
	CommunityCards []string `protobuf:"bytes,2,rep,name=community_cards,json=communityCards,proto3" json:"community_cards,omitempty"`  // Known community cards
	NumSimulations int32    `protobuf:"varint,3,opt,name=num_simulations,json=numSimulations,proto3" json:"num_simulations,omitempty"` // Number of Monte Carlo simulations
}

func (x *SimRequest) Reset() {
	*x = SimRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_poker_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimRequest) ProtoMessage() {}

func (x *SimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poker_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimRequest.ProtoReflect.Descriptor instead.
func (*SimRequest) Descriptor() ([]byte, []int) {
	return file_proto_poker_proto_rawDescGZIP(), []int{4}
}

func (x *SimRequest) GetHoleCards() []string {
	if x != nil {
		return x.HoleCards
	}
	return nil
}

func (x *SimRequest) GetCommunityCards() []string {
	if x != nil {
		return x.CommunityCards
	}
	return nil
}

func (x *SimRequest) GetNumSimulations() int32 {
	if x != nil {
		return x.NumSimulations
	}
	return 0
}

type SimResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinProbability  float64 `protobuf:"fixed64,1,opt,name=win_probability,json=winProbability,proto3" json:"win_probability,omitempty"`
	TieProbability  float64 `protobuf:"fixed64,2,opt,name=tie_probability,json=tieProbability,proto3" json:"tie_probability,omitempty"`
	LoseProbability float64 `protobuf:"fixed64,3,opt,name=lose_probability,json=loseProbability,proto3" json:"lose_probability,omitempty"`
	SimulationsRun  int32   `protobuf:"varint,4,opt,name=simulations_run,json=simulationsRun,proto3" json:"simulations_run,omitempty"`
}

func (x *SimResponse) Reset() {
	*x = SimResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_poker_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse) ProtoMessage() {}

func (x *SimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poker_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse.ProtoReflect.Descriptor instead.
func (*SimResponse) Descriptor() ([]byte, []int) {
	return file_proto_poker_proto_rawDescGZIP(), []int{5}
}

func (x *SimResponse) GetWinProbability() float64 {
	if x != nil {
		return x.WinProbability
	}
	return 0
}

func (x *SimResponse) GetTieProbability() float64 {
	if x != nil {
		return x.TieProbability
	}
	return 0
}

func (x *SimResponse) GetLoseProbability() float64 {
	if x != nil {
		return x.LoseProbability
	}
	return 0
}

func (x *SimResponse) GetSimulationsRun() int32 {
	if x != nil {
		return x.SimulationsRun
	}
	return 0
}

var File_proto_poker_proto protoreflect.FileDescriptor

var file_proto_poker_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x22, 0x55, 0x0a, 0x0b, 0x48, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x6f, 0x6c,
	0x65, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x68,
	0x6f, 0x6c, 0x65, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d,
	0x75, 0x6e, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x61, 0x72, 0x64,
	0x73, 0x22, 0x7b, 0x0a, 0x0c, 0x48, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x24, 0x0a, 0x0e, 0x62, 0x65, 0x73, 0x74, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x65, 0x73, 0x74, 0x48,
	0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x68, 0x61, 0x6e, 0x64, 0x5f,
	0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0d, 0x68, 0x61, 0x6e, 0x64, 0x52, 0x61, 0x6e, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x62, 0x65, 0x73, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x09, 0x62, 0x65, 0x73, 0x74, 0x43, 0x61, 0x72, 0x64, 0x73, 0x22, 0x64,
	0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x28, 0x0a, 0x05, 0x68, 0x61, 0x6e, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x05, 0x68, 0x61, 0x6e, 0x64, 0x31, 0x12, 0x28, 0x0a, 0x05, 0x68, 0x61,
	0x6e, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6f, 0x6b, 0x65,
	0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x05, 0x68,
	0x61, 0x6e, 0x64, 0x32, 0x22, 0x99, 0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x6e,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72,
	0x12, 0x36, 0x0a, 0x0c, 0x68, 0x61, 0x6e, 0x64, 0x31, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x48,
	0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x68, 0x61, 0x6e,
	0x64, 0x31, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x36, 0x0a, 0x0c, 0x68, 0x61, 0x6e, 0x64,
	0x32, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x0b, 0x68, 0x61, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x7d, 0x0a, 0x0a, 0x53, 0x69, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x68, 0x6f, 0x6c, 0x65, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x09, 0x68, 0x6f, 0x6c, 0x65, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x27, 0x0a,
	0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x6e, 0x75, 0x6d, 0x5f, 0x73, 0x69,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0e, 0x6e, 0x75, 0x6d, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0xb3, 0x01, 0x0a, 0x0b, 0x53, 0x69, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x27, 0x0a, 0x0f, 0x77, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x77, 0x69, 0x6e, 0x50, 0x72, 0x6f,
	0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x69, 0x65, 0x5f,
	0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0e, 0x74, 0x69, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x12, 0x29, 0x0a, 0x10, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0f, 0x6c, 0x6f, 0x73,
	0x65, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x27, 0x0a, 0x0f,
	0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x72, 0x75, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x75, 0x6e, 0x32, 0xc5, 0x01, 0x0a, 0x0c, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61,
	0x74, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x48,
	0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x6f, 0x6b,
	0x65, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3d, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x12,
	0x15, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d,
	0x0a, 0x14, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x11, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x53,
	0x69, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x6f, 0x6b, 0x65,
	0x72, 0x2e, 0x53, 0x69, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_poker_proto_rawDescOnce sync.Once
	file_proto_poker_proto_rawDescData = file_proto_poker_proto_rawDesc
)

func file_proto_poker_proto_rawDescGZIP() []byte {
	file_proto_poker_proto_rawDescOnce.Do(func() {
		file_proto_poker_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_poker_proto_rawDescData)
	})
	return file_proto_poker_proto_rawDescData
}

var file_proto_poker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_poker_proto_goTypes = []interface{}{
	(*HandRequest)(nil),     // 0: poker.HandRequest
	(*HandResponse)(nil),    // 1: poker.HandResponse
	(*CompareRequest)(nil),  // 2: poker.CompareRequest
	(*CompareResponse)(nil), // 3: poker.CompareResponse
	(*SimRequest)(nil),      // 4: poker.SimRequest
	(*SimResponse)(nil),     // 5: poker.SimResponse
}
var file_proto_poker_proto_depIdxs = []int32{
	0, // 0: poker.CompareRequest.hand1:type_name -> poker.HandRequest
	0, // 1: poker.CompareRequest.hand2:type_name -> poker.HandRequest
	1, // 2: poker.CompareResponse.hand1_result:type_name -> poker.HandResponse
	1, // 3: poker.CompareResponse.hand2_result:type_name -> poker.HandResponse
	0, // 4: poker.PokerService.EvaluateHand:input_type -> poker.HandRequest
	2, // 5: poker.PokerService.CompareHands:input_type -> poker.CompareRequest
	4, // 6: poker.PokerService.CalculateProbability:input_type -> poker.SimRequest
	1, // 7: poker.PokerService.EvaluateHand:output_type -> poker.HandResponse
	3, // 8: poker.PokerService.CompareHands:output_type -> poker.CompareResponse
	5, // 9: poker.PokerService.CalculateProbability:output_type -> poker.SimResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_poker_proto_init() }
func file_proto_poker_proto_init() {
	if File_proto_poker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_poker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_poker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_poker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_poker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_poker_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_poker_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_poker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_poker_proto_goTypes,
		DependencyIndexes: file_proto_poker_proto_depIdxs,
		MessageInfos:      file_proto_poker_proto_msgTypes,
	}.Build()
	File_proto_poker_proto = out.File
	file_proto_poker_proto_rawDesc = nil
	file_proto_poker_proto_goTypes = nil
	file_proto_poker_proto_depIdxs = nil
}
